### ISSUE TITLE
JDK 8 support

### ISSUE THREAD

**Issue by mims-github** [janhicken/surefire-scalatest#31]
Hi 
Thanks a lot for sharing this very useful maven surefire plugin.

Sadly, we still need to use JDK 8, so we can not use your plugin as is.
I just tested and think it's just the test `ScalaTestProviderTest` written in Java, which is not JDK 8 compatible.

Would you appreciate a contribution which adds JDK 8 support?
 
 Thanks!

**Comment by janhicken** [comment]
This has been fixed in version `0.3`.

**Comment by mims-github** [comment]
@janhicken Awesome, thanks a lot for the quick release. Will try it immediately. ;)
Very appreciated. 👏
